import java.math.BigInteger;
import java.util.HashSet;

public class Euler29 {



    // PROBLEM DEFINITION
    // Given the form a^b, how many distinct elements are there in a sequence for generated by 2 ≤ a ≤ 100, 2 ≤ b ≤ 100?

    // THOUGHTS
    // 1. These numbers will be way too big for int, long, or even double. max is literally 100 googols. BigInt is the only way.

    // This was way too easy using BigInteger
    // TODO: Retry this without BigInteger or other helpers


    static void main() {

        HashSet<BigInteger> distinctPowers = new HashSet<>();

        for (int a = 2; a <= 100; a++) {
            for (int b = 2; b <= 100; b++) {
                distinctPowers.add(BigInteger.valueOf(a).pow(b));
            }
        }

        System.out.println(distinctPowers.size());
    }

}
